version: '3'
volumes:
    mysql_volume:
    fastapi_volume:
services:
  db:
    image: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"      

  fastapi:
    image: fastapi-tf-torch-gpu
    volumes:
      - fastapi_volume:/app
    ports:
      - "8000:8000"
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
          - driver: "nvidia"
            device_ids: ["0"]
            capabilities: [gpu]